Repository googleapis/python-dns, pull requests merged in 2021-04, with the labels that each got.

#43 chore: start tracking obsolete files
  synth.metadata
Labels: api: dns, cla: yes, context: full

#44 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#46 chore: prevent normalization of semver versioning
  setup.py
Labels: api: dns, cla: yes

#47 chore(revert): revert preventing normalization
  setup.py
Labels: api: dns, cla: yes

#48 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  renovate.json
  synth.metadata
Labels: api: dns, automerge, cla: yes
